version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://jhonnypostgres:5432/java_jenkins
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: solocali123#
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - mi_red

networks:
  mi_red:
    external: true  # Si la red ya existe en Docker
